config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users

  resources :auctions do
    resources :bids, only: [:create]
    collection do
      get :my
    end
    member do
      get :end
    end
  end

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :user
  belongs_to :categories
  has_many :bids
  has_many :photos

  validates :initial_price, presence: true

  def end
    self.ended_at = Time.now
    if self.bids.any?
      self.winner_id = self.bids.last.user_id
    end
    self.save
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :auction
  belongs_to :users
  has_one :bid

  # validate :price_is_high_enough

  # def price_is_high_enough(max_price, current_price)
    
  # end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :auctions
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  has_one :user
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :auction
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :auctions
  has_one :setting
  has_many :opinions
  has_many :bids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_filter :user_signed_in?

  def index
    @auctions = Auction.all
  end

  def my
    @auctions = current_user.auctions
  end

  def end
    @auction = Auction.find(params[:id])
    @auction.end
    redirect_to my_auctions_path
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user_id = current_user.id
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def update
    @auction = Auction.find(params[:id])
    if @auction.update(auction_params)
      redirect_to my_auctions_path
    end
  end

  def show
    @auction = Auction.find(params[:id])
    @bid = @auction.bids.build
    @current_price = @auction.initial_price
    @bids = @auction.bids.all
  end


  private

  def auction_params
    params.require(:auction).permit(:name, :description, :initial_price, :starts_at, :end_time, :user_id)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  
  # def new
  #   @auction = Auction.find(params[:id])
  #   @bid = @auction.bids.build
  # end

  def create
    @auction = Auction.find(params[:auction_id])
    @bid = @auction.bids.new(bids_params)
    @bid.user_id = current_user.id
    @bid.current_price = @auction.initial_price + 1
    if @bid.save
      redirect_to auction_path(@auction)
    else
      # render 'auctions#show'
    end
  end

  private
  def bids_params
    params[:bid].permit(:max_price, :user_id, :auction_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user.email
    @auctions = Auction.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/my.html.haml
.container
  %table.table.table-striped
    %tr
      %th Photos
      %th Name
      %th Price
      %th
      %th Winner
    - @auctions.each do |auction|
      %tr
        %td
        %td= link_to auction.name, auction_path(auction)
        %td= auction.initial_price
        - if auction.ended_at.present?
          %td
            .btn.btn-info.btn-xs Ended       
        - else
          %td= link_to "End auction", end_auction_path(auction) ,class: 'btn btn-danger btn-xs'
        %td= auction.winner_id

app/views/auctions/new.html.haml
.container
  = simple_form_for @auction do |f|
    .input
      = f.input :name, :placeholder => "Title"
      = f.input :description, :placeholder => "Description"
      = f.input :initial_price
      .container
        .input-group
          = f.input :starts_at
          = f.input :end_time
    .actions
      = f.button :submit, class: "btn btn-success"

app/views/auctions/show.html.haml
.container
  %h1
    = @auction.name
  %table.table
    %tr
      %th User
      %td= @auction.user_id
    %tr
      %th Description
      %td
        = @auction.description
    %tr
      %th Current price
      %td
        = @current_price

.container
  %table.table.table-striped
    %tr
      %th Date
      %th User
      %th Price
    - @bids.each do |bid|
      %tr 
        %td= bid.created_at
        %td= bid.user_id
        %td= bid.max_price



.container
  = simple_form_for @bid, url: auction_bids_path(auction_id: @auction.id) do |f|
    .input
      = f.input :max_price
    .actions
      = f.button :submit, "Submit", class: 'btn btn-success'

app/views/home/index.html.haml
.container
  %h4 
    Logged as:
    = @user

  - if current_user
    = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm'
  - else 
    = link_to "Sign_in", sign_in_path, class: 'btn btn-success btn-sm'

  = link_to "New auction", new_auction_path, class: 'btn btn-primary btn-sm'

%br

.container
  %table.table.table-striped
    %tr
      %th Photos
      %th Name
      %th Price
      %th User
      %th
    - @auctions.each do |auction|
      %tr
        %td
        %td= link_to auction.name, auction_path(auction)
        %td= auction.initial_price
        %td= auction.user.email
        - if auction.ended_at.present?
          %td
            .btn.btn-danger.btn-xs Ended 
        - else       
          %td= link_to "Buy", auction_path(auction), class: 'btn btn-primary btn-xs'

= link_to "My auctions", my_auctions_path

app/views/home/index1.html.erb
<h4> Logged as: <%= @user %></h4>

<div class="container" style="text-align: right">
  <% if current_user %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm' %>
  <% else %>
    <%= link_to "Sign_in", sign_in_path, class: 'btn btn-success btn-sm' %>
  <% end %>


  <%= link_to "New auction", new_auction_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Allegro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1 class="text-center"> <%= link_to "Allegro", root_path%> </h1>

<%= yield %>

</body>
</html>